In [105]:
#with open ('./drive/MyDrive/Read.md','w') as f:
#    data = f.write("*반갑습니다")
#    print("저장되었습니다")
#!pwd

- ndim : 축의 갯수
- shape : 배열의 차원정보
- size : 배열안에 있는 원소의 총 갯수
- dtype : 배열 원소의 자료형

# 넘파이(numpy)

## 1차원과 속성들

In [106]:
#pip install numpy
import numpy as np
narry = np.array(range(5))
print(narry)
print(type(narry))
print(narry.ndim)#1차원
print(narry.shape)
print(narry.size)
print(narry.dtype)
print(narry[4])
print(narry[2:4])
#넘파이는 배열과 다르게 쉼표가 없다

[0 1 2 3 4]
<class 'numpy.ndarray'>
1
(5,)
5
int64
4
[2 3]


In [107]:
narr1 = np.array([1,2,3,4,5])
narr2 = np.array([2,3,'a','b'])
narr3 = np.array([2,3,'a','b'],dtype='str')
print(narr1,narr1.dtype)
print(narr2,narr2.dtype)
print(narr3,narr3.dtype)

[1 2 3 4 5] int64
['2' '3' 'a' 'b'] <U21
['2' '3' 'a' 'b'] <U1


In [108]:
#1차원 배열
narr4 = np.zeros((2,2),dtype="int64")
narr5 = np.ones((2,2))
narr6 = np.full((3,3),3)
narr7 = np.full((3,3),"number")
narr8 = np.eye(3) #단위행렬 만들때
narr9 = np.linspace(0,100,5)#range와 다르게 뒤에 수가 포함되어있다.
narr10 = np.linspace(0,100,5,endpoint=False,dtype='int64')#endpoint를 사용하면 마지막 수를 뺄수있다.
narr11 = np.arange(0,100,20)#마지막 수는 빠진다
print(narr4,narr4.ndim,narr4.dtype,narr4.shape,narr4.size,type(narr4))
print(narr5,narr5.ndim,narr5.dtype,narr5.shape,narr5.size,type(narr5))
print(narr6,narr6.ndim,narr6.dtype,narr6.shape,narr6.size,type(narr6))
print(narr7,narr7.ndim,narr7.dtype,narr7.shape,narr7.size,type(narr7))
print(narr8,narr8.ndim,narr8.dtype,narr8.shape,narr8.size,type(narr8))
print(narr9,narr9.ndim,narr9.dtype,narr9.shape,narr9.size,type(narr9))
print(narr10,narr10.ndim,narr10.dtype,narr10.shape,narr10.size,type(narr10))
print(narr11,narr11.ndim,narr11.dtype,narr11.shape,narr11.size,type(narr11))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'>
[  0.  25.  50.  75. 100.] 1 float64 (5,) 5 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>


## 2차원 배열

In [109]:
#print(list(range(2,10)))
print(np.arange(2,10))
range(10)
np.arange(10)

[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
#2차원 배열
arr1 = np.array([[0,0],[0,0]])
print(arr1,arr1.ndim,arr1.dtype,arr1.shape,arr1.size,type(arr1))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>


In [111]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr3 = np.arange(1,10).reshape(3,3)
arr4 = np.arange(1,11).reshape(2,5)
arr5 = np.arange(1,11).reshape(5,2)
arr6 = np.arange(1,28).reshape(3,3,3) #3차원
print("차원 :",arr2.ndim,'/',"데이터 타입 :",arr2.dtype,'/',"형태 :",arr2.shape,'/',"크기 :",arr2.size,'/',type(arr2),'\n',arr2,'\n')
print("차원 :",arr3.ndim,'/',"데이터 타입 :",arr3.dtype,'/',"형태 :",arr3.shape,'/',"크기 :",arr3.size,'/',type(arr3),'\n',arr3,'\n')
print("차원 :",arr4.ndim,'/',"데이터 타입 :",arr4.dtype,'/',"형태 :",arr4.shape,'/',"크기 :",arr4.size,'/',type(arr4),'\n',arr4,'\n')
print("차원 :",arr5.ndim,'/',"데이터 타입 :",arr5.dtype,'/',"형태 :",arr5.shape,'/',"크기 :",arr5.size,'/',type(arr5),'\n',arr5,'\n')
print("차원 :",arr6.ndim,'/',"데이터 타입 :",arr6.dtype,'/',"형태 :",arr6.shape,'/',"크기 :",arr6.size,'/',type(arr6),'\n',arr6)

차원 : 2 / 데이터 타입 : int64 / 형태 : (3, 3) / 크기 : 9 / <class 'numpy.ndarray'> 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

차원 : 2 / 데이터 타입 : int64 / 형태 : (3, 3) / 크기 : 9 / <class 'numpy.ndarray'> 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

차원 : 2 / 데이터 타입 : int64 / 형태 : (2, 5) / 크기 : 10 / <class 'numpy.ndarray'> 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

차원 : 2 / 데이터 타입 : int64 / 형태 : (5, 2) / 크기 : 10 / <class 'numpy.ndarray'> 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 

차원 : 3 / 데이터 타입 : int64 / 형태 : (3, 3, 3) / 크기 : 27 / <class 'numpy.ndarray'> 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [112]:
#예제
t1 = np.arange(1,22).reshape(3,7)
t2 = np.arange(1,8).reshape(7,1)
t3 = np.arange(1,11).reshape(5,2)
t4 = np.arange(1,22).reshape(3,7)
t5 = np.arange(1,13).reshape(4,3,1)
# 2차원 reshape의 팁은 reahape(세로,가로)라고 생각하면 편하다
# 3차원은 reshape(공간,세로,가로)라고 생각하면 편하다
print(t1,'\n',end="="*20)
print('\n',t2,'\n',end="="*20)
print('\n',t3,'\n',end="="*20)
print('\n',t4,'\n',end="="*20)
print('\n',t5)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]] 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]] 
 [[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [113]:
#for i in range(0,3):
#  print(t1[i][3:7])
print(t1[1][2:5])#슬라이싱도 가능
print(t4[1:3,4:6])
print(t4[t4>12])
print(t4%2 ==0)

[10 11 12]
[[12 13]
 [19 20]]
[13 14 15 16 17 18 19 20 21]
[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]]


In [114]:
#np 배열 연산 // shape가 같을 경우 원소별 연산이 가능
np1 = np.array([6,7,8,9,10])
np2 = np.array([1,2,3,4,5])
print("덧셈 :",np1+np2)
print("뺄셈 :",np1-np2)
print("곱셈 :",np1*np2)
print("나눗셈 :",np1/np2)

덧셈 : [ 7  9 11 13 15]
뺄셈 : [5 5 5 5 5]
곱셈 : [ 6 14 24 36 50]
나눗셈 : [6.         3.5        2.66666667 2.25       2.        ]


In [115]:
#브로드캐스팅
np3 = np1 + 10
print(np3)

[16 17 18 19 20]


In [116]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33]).reshape(3,1)#reshape를 (3,1)로 지정하면 형태가 변하기 때문에 값이 닫라진다.
#스칼라와 연산
print(br1)
print()
print(br2)
print()
print("===↓스칼라와 연산↓===")
print(br1*2)
print()
print(br1*3)
print()
#2d와 3d의 연산
print("===↓2d와 3d의 연산↓===")
print(br1+br2)
print()
print(br1*br2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[11]
 [22]
 [33]]

===↓스칼라와 연산↓===
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]

===↓2d와 3d의 연산↓===
[[12 13 14]
 [26 27 28]
 [40 41 42]]

[[ 11  22  33]
 [ 88 110 132]
 [231 264 297]]


In [117]:
ff = np.arange(1,10).reshape(3,3)
print(ff)
print(ff.reshape(9))
print(ff.flatten())
#flatten은 행렬안의 값을 풀어서 일렬로 세운다.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


## Random number 발생

- np.random.randint(): 균일 분포의 정수 난수
- np.random.rand(): 0부터 1사이의 균일 분포 난수 생성
- np.random.randn(): 표준 정규 분포 난수 생성
- np.random.normal(): 정규 분포 난수 생성

In [118]:
#randint()
import numpy as np
x = np.random.randint(0,225,size=(3,3,3))
x

array([[[ 30,   2,  88],
        [  7,  63,  24],
        [217,  28, 121]],

       [[113, 154, 194],
        [165, 109, 151],
        [201,  21, 186]],

       [[ 63, 100,  24],
        [130, 203,  81],
        [ 58,  17, 176]]], dtype=int32)

In [119]:
print("평균값 :", np.mean(x),"표준편차 :",np.std(x))

평균값 : 100.96296296296296 표준편차 : 68.2698792003887


In [120]:
print(len(x.flatten()))

27


In [121]:
y = np.array([0,1,2,3,6,5,4,2,3,54,3,54,8,5,11,864,3,1,4,3,2,543,2,1,5,3,2]).reshape(3,3,3)
print(y)
print(len(y))
print(np.count_nonzero(y))

[[[  0   1   2]
  [  3   6   5]
  [  4   2   3]]

 [[ 54   3  54]
  [  8   5  11]
  [864   3   1]]

 [[  4   3   2]
  [543   2   1]
  [  5   3   2]]]
3
26


## random number 발생

In [16]:
#설정한 범위 안에서 균일 분포 난수 생성
x = np.random.randint(1,5,size=(10,5))
x

array([[3, 2, 1, 3, 2],
       [1, 4, 3, 1, 1],
       [4, 2, 4, 3, 4],
       [3, 3, 3, 2, 4],
       [2, 3, 3, 1, 2],
       [3, 2, 3, 4, 2],
       [1, 2, 2, 1, 3],
       [4, 1, 4, 1, 4],
       [2, 3, 3, 1, 1],
       [3, 2, 1, 3, 4]], dtype=int32)

In [18]:
#0에서 1사이의 균일 분포 난수 생성
x = np.random.rand(10,5)
x

array([[0.75946249, 0.64385777, 0.59680306, 0.12423724, 0.2961783 ],
       [0.53182082, 0.81009873, 0.42954732, 0.05221746, 0.83776063],
       [0.2167844 , 0.02807525, 0.18182573, 0.10339811, 0.02903265],
       [0.75318123, 0.85945912, 0.33577356, 0.56302878, 0.9279127 ],
       [0.90998867, 0.22681657, 0.67870318, 0.41688122, 0.31843095],
       [0.04712551, 0.32028968, 0.73948174, 0.71467936, 0.36470907],
       [0.16601108, 0.81865989, 0.15981354, 0.30013242, 0.29592586],
       [0.12677678, 0.97343978, 0.88551716, 0.71713637, 0.31355489],
       [0.54627562, 0.84900628, 0.44251916, 0.97371641, 0.27415816],
       [0.3206836 , 0.29218251, 0.60456126, 0.99427109, 0.60276777]])

In [34]:
#평균과 표준편차를 가지고 정규분포 난수 생성
x = np.random.normal(5,3,size=(10,5)) #평균이 5 표준편차가 3
#print(x)
print(np.mean(x)) #평균
print(np.std(x)) #표쥰편차
print(x.max()) 
print(x.min())

4.983554278760117
2.8176239049214145
10.617332377450415
-1.3810446400974739


In [35]:
x =np.array([5,3,21,3,6,1,6,4,6,1,2,5,3,35,35,65,1,351,651,65])
print("x의 갯수",len(x))
print("x의 갯수",np.count_nonzero(x))
print("0의 갯수",len(x) - np.count_nonzero(x))

x의 갯수 20
x의 갯수 20
0의 갯수 0


In [38]:
print(np.mean(x))
print(x.mean())
print(np.median(x))

63.45
63.45
5.5


In [39]:
print(np.percentile(x,0)) #최소값
print(np.percentile(x,25)) #제1사분위수
print(np.percentile(x,50)) #중앙값, 제2사분위수
print(np.percentile(x,75)) #제3사분위수
print(np.percentile(x,100)) #최대값

1.0
3.0
5.5
35.0
651.0


# 판다스(pandas)

- 시리즈(series) - 단수
- 데이터프레임(dataframe) - 복수

In [2]:
#판다스 시리즈의 기초(numpy값 사용), 데이터 타입
import numpy as np
import pandas as pd

data1 = np.arange(1,6)
#print(data1)

data2 = pd.Series(data1)
#판다스 시리즈는 기본적으로 좌측 인덱스 값 우측은 데이터값이다.
data3 = pd.Series([1,2,3,4,5,6,7])#, dtype="float") 하나의 데이터 값을 기준으로 출력값의 형태를 동일시함
# 만약 값 안에 소수가 있으면 전원 float 전원 정수라면 int형태로 나오는 것이다.
print(data2, type(data2), data2.values, data2.dtype,"\n", data2.index)
print(data3)


0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.core.series.Series'> [1 2 3 4 5] int64 
 RangeIndex(start=0, stop=5, step=1)
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64


In [123]:
# 판다스 시리즈의 인덱스설정
data3 = pd.Series([1,2,3,4,5,6,7], index=["a","b","c","d","e","f","g"])
print(data3)

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64


In [5]:
#판다스 시리즈 딕셔너리데이터 
population_dict ={
    "korea":5182,
    "japan":12622,
    "china":141178,
    "usa":32976
}
#population_dict.keys()
#population_dict.values()
#population_dict.items()
country = pd.Series(population_dict)
#print(country, country.index, country.values)
#print(country.ndim, country.shape, country.size)
# ※ 온점뒤에 오는 기능들중 ()가 들어가는건 그거에 기능을 뜻하고 ()가 없는건 특징 속성을 내는것이다.

#판다스 시리즈 원소에 접근방법
print(country.loc["korea"])
print(country.iloc[0])

5182


In [125]:
#판다스 데이터 프레임
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], index=["a","b","c"], columns=["A","B","C"])
# 판다스 데이터 프레임은 값을 표처럼 만들어준다.
# 여기서 인덱스는 세로 값 이름, 컬럼스는 가로 값 이름을 정할 수 있다.
df

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [2]:
#테스트
import numpy as np
import pandas as pd

#두 개의 시리즈 데이터
print("인구수 시리즈 데이터 :")
population_dict ={
    "korea":5182,
    "japan":12622,
    "china":141178,
    "usa":32976
}
population = pd.Series(population_dict)
print(population)
print()
print("GDP 시리즈 데이터 :")
GDP_dict ={
    "korea":169320000,
    "japan":516700000,
    "china":140925000,
    "usa":2041280000
}
GDP = pd.Series(GDP_dict)
print(GDP)
print("="*25)
print("데이터 프레임 생성")
country = pd.DataFrame({"population":population,"gdp":GDP})
country.index.name ="Country" #인덱스 이름 지정
country.columns.name = "INFO" #컬럼 이름지정
print(country.index, country.columns, country.values)
print(country.shape, country.ndim, country.size)

인구수 시리즈 데이터 :
korea      5182
japan     12622
china    141178
usa       32976
dtype: int64

GDP 시리즈 데이터 :
korea     169320000
japan     516700000
china     140925000
usa      2041280000
dtype: int64
데이터 프레임 생성
Index(['korea', 'japan', 'china', 'usa'], dtype='object', name='Country') Index(['population', 'gdp'], dtype='object', name='INFO') [[      5182  169320000]
 [     12622  516700000]
 [    141178  140925000]
 [     32976 2041280000]]
(4, 2) 2 8


In [4]:
#데이터 프레임의 요소 접근방법, loc ,iloc
country.loc["korea"],country.loc["usa"]
#loc는 2개의 값을 지정해서 출력 행과 열을 입력하면 그 값을 가져올수있다.
country.iloc[2],country.iloc[1]

(INFO
 population       141178
 gdp           140925000
 Name: china, dtype: int64,
 INFO
 population        12622
 gdp           516700000
 Name: japan, dtype: int64)

In [128]:
country.loc["korea":"china",:"population"]

INFO     population
Country            
korea          5182
japan         12622
china        141178

In [129]:
country.iloc[0:2,:1]

INFO     population
Country            
korea          5182
japan         12622

In [130]:
country.iloc[1:4,1:]

INFO            gdp
Country            
japan     516700000
china     140925000
usa      2041280000

In [131]:
country.iloc[1:3]

INFO     population        gdp
Country                       
japan         12622  516700000
china        141178  140925000

In [132]:
#데이터 프레임의 컬럼 생성방법
#country["test"]=[11,22,33,44]
#country.drop("test",axis=1) # 컬럼을 지울 때 사용 axis는 열과 행을 지정 0는 행을 1은 열을 제거
gdpper = country["gdp"] / country["population"]
country["gdp_per"]= gdpper
country


INFO     population         gdp       gdp_per
Country                                      
korea          5182   169320000  32674.642995
japan         12622   516700000  40936.460149
china        141178   140925000    998.207936
usa           32976  2041280000  61901.989326

In [136]:
#데이터 프레임의 인덱스 생성방법 1
country.loc["india"] = [14222,1505050000,12121212]
country.loc["india","gdp_per"] = country.loc["india","gdp"]/country.loc["india","population"]
country

INFO     population         gdp        gdp_per
Country                                       
korea          5182   169320000   32674.642995
japan         12622   516700000   40936.460149
china        141178   140925000     998.207936
usa           32976  2041280000   61901.989326
india         14222  1505050000  105825.481648

In [138]:
#데이터 프레임의 인덱스 생성방법 2
africa = pd.Series(data=[123456,777777],index=["population","gdp"])
country.loc["africa"]=africa
country


INFO     population           gdp        gdp_per
Country                                         
korea        5182.0  1.693200e+08   32674.642995
japan       12622.0  5.167000e+08   40936.460149
china      141178.0  1.409250e+08     998.207936
usa         32976.0  2.041280e+09   61901.989326
india       14222.0  1.505050e+09  105825.481648
africa     123456.0  7.777770e+05            NaN

In [140]:
country.isnull().sum()

INFO
population    0
gdp           0
gdp_per       1
dtype: int64

In [ ]:
# 열제거 drop(이름,exis=0)
country.drop("africa",axis=0)#inplace = Ture
country

In [ ]:
#테스트 1 조건
country[country["population"]>140000]

In [ ]:
#테스트 2 조건, 슬라이싱(loc,iloc필수)
country[(country["population"]>10000) & (country["population"] < 100000)].loc[:,:"population"]

INFO     population
Country            
japan       12622.0
usa         32976.0
india       14222.0

In [240]:
data1 = pd.DataFrame([[80,70,80],[60,70,80],[70,90,80]],index = ["홍길동","박철수","김영희"],columns=["국어","수학","영어"])
data1

국어  수학  영어
홍길동  80  70  80
박철수  60  70  80
김영희  70  90  80

In [241]:
data1.iloc[1:2,:2]

국어  수학
박철수  60  70

In [242]:
data1[data1["수학"]>=70]

국어  수학  영어
홍길동  80  70  80
박철수  60  70  80
김영희  70  90  80

In [243]:
average = (data1["국어"]+data1["수학"]+data1["영어"])/3
data1["평균"] = average
data1

국어  수학  영어         평균
홍길동  80  70  80  76.666667
박철수  60  70  80  70.000000
김영희  70  90  80  80.000000

In [244]:
a = pd.Series(data=[55,95,70],index=["국어","수학","영어",])
data1.loc["최자바"]=a
average = (data1["국어"]+data1["수학"]+data1["영어"])/3
data1["평균"] = average
data1


국어    수학    영어         평균
홍길동  80.0  70.0  80.0  76.666667
박철수  60.0  70.0  80.0  70.000000
김영희  70.0  90.0  80.0  80.000000
최자바  55.0  95.0  70.0  73.333333

In [247]:
import numpy as np
data = np.array([["홍길동",80,70,80],["박철수",60,70,80],["김영희",70,90,80]])
print(data)

[['홍길동' '80' '70' '80']
 ['박철수' '60' '70' '80']
 ['김영희' '70' '90' '80']]


In [ ]:
data [data["국어"].dtype(data)]