In [ ]:
#with open ('./drive/MyDrive/Read.md','w') as f:
#    data = f.write("*반갑습니다")
#    print("저장되었습니다")
#!pwd

- ndim : 축의 갯수
- shape : 배열의 차원정보
- size : 배열안에 있는 원소의 총 갯수
- dtype : 배열 원소의 자료형

# 넘파이(numpy)

In [23]:
#pip install numpy
import numpy as np
narry = np.array(range(5))
print(narry)
print(type(narry))
print(narry.ndim)#1차원
print(narry.shape)
print(narry.size)
print(narry.dtype)
print(narry[4])
print(narry[2:4])
#넘파이는 배열과 다르게 쉼표가 없다

[0 1 2 3 4]
<class 'numpy.ndarray'>
1
(5,)
5
int64
4
[2 3]


In [24]:
narr1 = np.array([1,2,3,4,5])
narr2 = np.array([2,3,'a','b'])
narr3 = np.array([2,3,'a','b'],dtype='str')
print(narr1,narr1.dtype)
print(narr2,narr2.dtype)
print(narr3,narr3.dtype)

[1 2 3 4 5] int64
['2' '3' 'a' 'b'] <U21
['2' '3' 'a' 'b'] <U1


In [117]:
#1차원 배열
narr4 = np.zeros((2,2),dtype="int64")
narr5 = np.ones((2,2))
narr6 = np.full((3,3),3)
narr7 = np.full((3,3),"number")
narr8 = np.eye(3) #단위행렬 만들때
narr9 = np.linspace(0,100,5)#range와 다르게 뒤에 수가 포함되어있다.
narr10 = np.linspace(0,100,5,endpoint=False,dtype='int64')#endpoint를 사용하면 마지막 수를 뺄수있다.
narr11 = np.arange(0,100,20)#마지막 수는 빠진다
print(narr4,narr4.ndim,narr4.dtype,narr4.shape,narr4.size,type(narr4))
print(narr5,narr5.ndim,narr5.dtype,narr5.shape,narr5.size,type(narr5))
print(narr6,narr6.ndim,narr6.dtype,narr6.shape,narr6.size,type(narr6))
print(narr7,narr7.ndim,narr7.dtype,narr7.shape,narr7.size,type(narr7))
print(narr8,narr8.ndim,narr8.dtype,narr8.shape,narr8.size,type(narr8))
print(narr9,narr9.ndim,narr9.dtype,narr9.shape,narr9.size,type(narr9))
print(narr10,narr10.ndim,narr10.dtype,narr10.shape,narr10.size,type(narr10))
print(narr11,narr11.ndim,narr11.dtype,narr11.shape,narr11.size,type(narr11))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'>
[  0.  25.  50.  75. 100.] 1 float64 (5,) 5 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>


# 2차원 배열

In [58]:
#print(list(range(2,10)))
print(np.arange(2,10))
range(10)
np.arange(10)

[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
#2차원 배열
arr1 = np.array([[0,0],[0,0]])
print(arr1,arr1.ndim,arr1.dtype,arr1.shape,arr1.size,type(arr1))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>


In [72]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr3 = np.arange(1,10).reshape(3,3)
arr4 = np.arange(1,11).reshape(2,5)
arr5 = np.arange(1,11).reshape(5,2)
arr6 = np.arange(1,28).reshape(3,3,3) #3차원
print("차원 :",arr2.ndim,'/',"데이터 타입 :",arr2.dtype,'/',"형태 :",arr2.shape,'/',"크기 :",arr2.size,'/',type(arr2),'\n',arr2,'\n')
print("차원 :",arr3.ndim,'/',"데이터 타입 :",arr3.dtype,'/',"형태 :",arr3.shape,'/',"크기 :",arr3.size,'/',type(arr3),'\n',arr3,'\n')
print("차원 :",arr4.ndim,'/',"데이터 타입 :",arr4.dtype,'/',"형태 :",arr4.shape,'/',"크기 :",arr4.size,'/',type(arr4),'\n',arr4,'\n')
print("차원 :",arr5.ndim,'/',"데이터 타입 :",arr5.dtype,'/',"형태 :",arr5.shape,'/',"크기 :",arr5.size,'/',type(arr5),'\n',arr5,'\n')
print("차원 :",arr6.ndim,'/',"데이터 타입 :",arr6.dtype,'/',"형태 :",arr6.shape,'/',"크기 :",arr6.size,'/',type(arr6),'\n',arr6)

차원 : 2 / 데이터 타입 : int64 / 형태 : (3, 3) / 크기 : 9 / <class 'numpy.ndarray'> 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

차원 : 2 / 데이터 타입 : int64 / 형태 : (3, 3) / 크기 : 9 / <class 'numpy.ndarray'> 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

차원 : 2 / 데이터 타입 : int64 / 형태 : (2, 5) / 크기 : 10 / <class 'numpy.ndarray'> 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

차원 : 2 / 데이터 타입 : int64 / 형태 : (5, 2) / 크기 : 10 / <class 'numpy.ndarray'> 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 

차원 : 3 / 데이터 타입 : int64 / 형태 : (3, 3, 3) / 크기 : 27 / <class 'numpy.ndarray'> 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [108]:
#예제
t1 = np.arange(1,22).reshape(3,7)
t2 = np.arange(1,8).reshape(7,1)
t3 = np.arange(1,11).reshape(5,2)
t4 = np.arange(1,22).reshape(3,7)
t5 = np.arange(1,13).reshape(4,3,1)
# 2차원 reshape의 팁은 reahape(세로,가로)라고 생각하면 편하다
# 3차원은 reshape(공간,세로,가로)라고 생각하면 편하다
print(t1,'\n',end="="*20)
print('\n',t2,'\n',end="="*20)
print('\n',t3,'\n',end="="*20)
print('\n',t4,'\n',end="="*20)
print('\n',t5)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]] 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]] 
 [[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [147]:
#for i in range(0,3):
#  print(t1[i][3:7])
print(t1[1][2:5])#슬라이싱도 가능
print(t4[1:3,4:6])
print(t4[t4>12])
print(t4%2 ==0)

[10 11 12]
[[12 13]
 [19 20]]
[13 14 15 16 17 18 19 20 21]
[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]]


In [151]:
#np 배열 연산 // shape가 같을 경우 원소별 연산이 가능
np1 = np.array([6,7,8,9,10])
np2 = np.array([1,2,3,4,5])
print("덧셈 :",np1+np2)
print("뺄셈 :",np1-np2)
print("곱셈 :",np1*np2)
print("나눗셈 :",np1/np2)

덧셈 : [ 7  9 11 13 15]
뺄셈 : [5 5 5 5 5]
곱셈 : [ 6 14 24 36 50]
나눗셈 : [6.         3.5        2.66666667 2.25       2.        ]


In [153]:
#브로드캐스팅
np3 = np1 + 10
print(np3)

[16 17 18 19 20]


In [166]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33]).reshape(3,1)#reshape를 (3,1)로 지정하면 형태가 변하기 때문에 값이 닫라진다.
#스칼라와 연산
print(br1)
print()
print(br2)
print()
print("===↓스칼라와 연산↓===")
print(br1*2)
print()
print(br1*3)
print()
#2d와 3d의 연산
print("===↓2d와 3d의 연산↓===")
print(br1+br2)
print()
print(br1*br2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[11]
 [22]
 [33]]

===↓스칼라와 연산↓===
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]

===↓2d와 3d의 연산↓===
[[12 13 14]
 [26 27 28]
 [40 41 42]]

[[ 11  22  33]
 [ 88 110 132]
 [231 264 297]]


In [170]:
ff = np.arange(1,10).reshape(3,3)
print(ff)
print(ff.reshape(9))
print(ff.flatten())
#flatten은 행렬안의 값을 풀어서 일렬로 세운다.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
